### ISSUE TITLE
Wrong p-norm

### ISSUE THREAD

**Issue by andreasnoack** [andyferris/TransposedVectors.jl#1]
I've been playing around with the package tonight and so far the approach seems to work. It's quite a few definitions just to get scalars out of `x'x` and `x'A*x` but if the work required doesn't propagate beyond the initial implementation then it shouldn't be a problem. I'll play more with the implementation in the near future.

I've found a few minor bugs. I believe the `p` norm should be the `q` of the non-transposed vector, i.e.
```jl
norm(x::TransposeVector, p) = norm(x.vec, p/(p-1))
```

**Comment by andyferris** [comment]
Thanks Andreas - it's good to have some more eyes on this.

> I believe the p norm should be the q of the non-transposed vector,

Sorry, could you elaborate? I thought it made sense that since a transposed vector is, in fact, a vector in some dual space, I thought the norms should both be `vecnorm`. I'm so used to `p == q == 2` - does your definition make more sense when you consider dual vectors in a more general context?

Keep in mind, this package doesn't fully combine the ideas of dual vectors and row vectors - the latter takes precedence since Julia (like MATLAB) still takes a quite "data-based" and array-based view on linear algebra types. For instance, these transposed vectors do not include complex conjugation. Nor does the transposition operator allow you to specify the norm/inner-product in any way (I guess `p=2` is assumed).

**Comment by andreasnoack** [comment]
The reasoning is the following. In the current implementation `x'` defines a functional and the norm on that functional is induced by the norm on the space on which the functional is defined (where `x` lives). To avoid any notational confusion with inner products (there is no need for inner product in this discussion) let's call the functional `f=x'`. So `norm(f, p)` should be `sup_y f*y` for `norm(y,p)==1` which happens to be `norm(x,p/(p-1))`. Notice that this happens to work perfectly for row and columns matrices for `p=1,∞`.

**Comment by andyferris** [comment]
Thanks, after your comment I was thinking it would be something like that, and yes I do notice that this already works for column and row matrices. Yes we should implement and document this.

**Comment by andyferris** [comment]
Fixed
