### ISSUE TITLE
Recursive transpose

### ISSUE THREAD

**Issue by andreasnoack** [andyferris/TransposedVectors.jl#4]
Right now, the transpose is not recursive so blocking doesn't work.
```jl
julia> x = [randn(2) for i = 1:3]
3-element Array{Array{Float64,1},1}:
 [1.43478,-0.559963]
 [-1.20678,0.711178]
 [-1.41482,1.0938]

julia> x'x
ERROR: Cannot multiply two vectors
 in collect(::Base.Generator{Base.Iterators.Zip2{Array{Array{Float64,1},1},Array{Array{Float64,1},1}},Base.##3#4{TransposedVectors.##5#6}}) at ./array.jl:366
 in Ac_mul_B(::Array{Array{Float64,1},1}, ::Array{Array{Float64,1},1}) at /Users/andreasnoack/.julia/v0.6/TransposedVectors/src/mul.jl:64
```

**Comment by andyferris** [comment]
Hmm... yes I was always a bit sceptical of that. Shouldn't be too difficult, I should think.

So you want a scalar for the inner product here?

**Comment by andreasnoack** [comment]
Yes. I think that would be the better behavior and is also what we have now.

Update: Well, right now it's a length one vector because of 4774 but it doesn't error.

**Comment by andyferris** [comment]
OK - there is a tricky issue here, were the element type of the array is changed because of the recursive transpose. Grr

It's actually a bit challenging to compute what the new element type should be, since now the elments are the transpose of the things we are taking a view of, and because `Core.Inference.return_type` is so flakey...

Grr

**Comment by andyferris** [comment]
OK this is one of those things where `promote_op` is helpful (via its workaround to use inference on `first` of a `Generator`, something which I never understood the reason for but oh well, it works).
